version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./.env
    working_dir: /netstats-server
    ports:
      - 3000:3000
    volumes:
      - ./:/netstats-server
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "grunt && WS_SECRET="4Qfj80ZXtfAhHjyEqN1Aoq7MvMZnSnwlr0SCScp4zqXvqynrmXoN7WeQyyYXgY" npm start"
